services:
  sentinelnet:
    image: claudiovidhi/sentinelnet:latest
    build: .
    container_name: sentinelnet
    ports:
      - "8765:8765"
    volumes:
      # Monta solo la cartella dei dati persistenti (db di autenticazione, credenziali degli apparati, chiavi crittografiche, backup)
      # Questo consente di distribuire ed eseguire l'applicazione come immagine standalone pre-compilata da Docker Hub
      # senza sovrascrivere o aver bisogno del codice sorgente Python locale.
      - ./data:/app/data
    environment:
      # Forza l'applicazione a salvare database, chiavi e backup all'interno della directory del volume condiviso
      - SENTINELNET_DATA_DIR=/app/data
      - SENTINELNET_HOST=0.0.0.0
      - SENTINELNET_PORT=8765
      - SENTINELNET_NO_BROWSER=true
      # - SENTINELNET_MASTER_KEY=chiave_segreta_fernet_personalizzata
      # - SENTINELNET_JWT_SECRET=chiave_segreta_jwt_personalizzata
      # - SENTINELNET_ADMIN_USER=Admin
      # - SENTINELNET_ADMIN_PASS=admin
      # - SENTINELNET_ADMIN_SECRET=admin
    restart: unless-stopped
